// 한의 난임 진료부(여성용) 초진 챠트 — ver4.0 PDF 1~6p 디지털화
import {
  INFERTILITY_CAUSE,
  PATTERN_FEMALE,
  SCALE_OPTIONS,
  YESNO,
  treatmentSection,
  type FormSchema,
} from './schema'

export const femaleInitial: FormSchema = {
  type: 'initial_female',
  title: '한의 난임 진료부(여성용) · 초진',
  sections: [
    {
      id: 'general',
      title: '일반정보 · 신체정보 · 기호품',
      fields: [
        { id: 'visit_date', label: '초진일자', kind: 'date', width: 'third', required: true },
        { id: 'height', label: '키', kind: 'number', unit: 'cm', width: 'third' },
        { id: 'weight', label: '몸무게', kind: 'number', unit: 'kg', width: 'third' },
        { id: 'caffeine', label: '커피 등 카페인음료', kind: 'text', unit: '잔/일', width: 'half' },
        { id: 'meds', label: '복용 중 약물', kind: 'text', width: 'half' },
        { id: 'alcohol', label: '음주', kind: 'text', placeholder: '술 ○병/회, 월 ○회', width: 'half' },
        {
          id: 'smoking',
          label: '흡연',
          kind: 'radio',
          options: ['비흡연', '금연', '흡연'],
          width: 'half',
        },
        { id: 'smoking_amount', label: '흡연량(흡연 시)', kind: 'text', unit: '개피/일', width: 'half' },
        { id: 'comorbidity', label: '동반질환', kind: 'textarea', width: 'full' },
        { id: 'surgery_history', label: '수술력', kind: 'textarea', width: 'full' },
      ],
    },
    {
      id: 'marriage_birth',
      title: '결혼 및 출산력',
      fields: [
        { id: 'marriage_period', label: '결혼기간', kind: 'number', unit: '개월', width: 'third' },
        { id: 'ttc_start', label: '임신시도 시작', kind: 'number', unit: '개월 전', width: 'third' },
        { id: 'contraception_period', label: '피임기간', kind: 'number', unit: '개월', width: 'third' },
        {
          id: 'intercourse_freq',
          label: '성생활 빈도',
          kind: 'text',
          placeholder: '평균 ○회/월 (배란 전/당일/후)',
          width: 'full',
        },
        {
          id: 'contraception_method',
          label: '피임방법',
          kind: 'checks',
          options: [
            '경구 피임제',
            '주사용 피임제',
            '피하 이식 피임제',
            '자궁 내 피임장치',
            '콘돔',
            '질외사정',
            '날짜 피임법',
          ],
          allowOther: true,
          width: 'full',
        },
        {
          id: 'obstetric_history',
          label: '산과력 (만삭-조산-유산-생존자녀)',
          kind: 'text',
          placeholder: '( ) - ( ) - ( ) - ( )',
          width: 'full',
        },
        {
          id: 'birth_history',
          label: '출산력 (출산시기 / 임신방법 / 출산방법)',
          kind: 'textarea',
          width: 'full',
        },
      ],
    },
    {
      id: 'dx_info',
      title: '난임 진단 및 치료정보',
      fields: [
        { id: 'dx_first_org', label: '난임 최초 진단기관명', kind: 'text', width: 'half' },
        { id: 'dx_time', label: '진단시기', kind: 'text', placeholder: 'YYYY-MM', width: 'half' },
        { id: 'h_exam', label: '— 여성 난임 검사결과 —', kind: 'heading' },
        { id: 'exam_us', label: '초음파 검사 (최근검사일 포함)', kind: 'textarea', width: 'full' },
        { id: 'horm_amh', label: 'AMH', kind: 'number', unit: 'ng/mL', width: 'quarter' },
        { id: 'horm_lh', label: 'LH', kind: 'number', unit: 'IU/L', width: 'quarter' },
        { id: 'horm_fsh', label: 'FSH', kind: 'number', unit: 'IU', width: 'quarter' },
        { id: 'horm_e2', label: 'E2', kind: 'number', unit: 'pg/mL', width: 'quarter' },
        { id: 'exam_laparoscopy', label: '복강경 검사', kind: 'text', width: 'half' },
        { id: 'exam_hsg', label: '난관조영술', kind: 'text', width: 'half' },
        { id: 'exam_autoab', label: '자가항체', kind: 'text', width: 'half' },
        { id: 'exam_etc', label: '기타 검사', kind: 'text', width: 'half' },
        { id: 'h_past', label: '— 여성 난임치료 과거력 —', kind: 'heading' },
        {
          id: 'past_ovulation',
          label: '일반/단순 배란유도',
          kind: 'textarea',
          placeholder: '최종시기 / 총 ○회 / 실패·임신·유산·출산',
          width: 'half',
        },
        {
          id: 'past_iui',
          label: '인공수정',
          kind: 'textarea',
          placeholder: '최종시기 / 총 ○회 / 실패·임신·유산·출산',
          width: 'half',
        },
        {
          id: 'past_ivf',
          label: '체외수정',
          kind: 'textarea',
          placeholder: '최종시기 / 총 ○회 / 실패·임신·유산·출산',
          width: 'half',
        },
        {
          id: 'past_acu',
          label: '한의 침치료',
          kind: 'textarea',
          placeholder: '최종시기 / 총 ○회 / 결과 / 치료기간 ○개월',
          width: 'half',
        },
        {
          id: 'past_herb',
          label: '한약치료',
          kind: 'textarea',
          placeholder: '최종시기 / 총 ○회 / 결과 / 치료기간 ○개월',
          width: 'half',
        },
        {
          id: 'past_etc',
          label: '기타치료',
          kind: 'textarea',
          placeholder: '최종시기 / 총 ○회 / 결과 / 치료기간 ○개월',
          width: 'half',
        },
      ],
    },
    {
      id: 'gyn_menses',
      title: '한의부인과적 평가 · 월경력',
      fields: [
        { id: 'lmp', label: 'LMP(마지막 월경시작일)', kind: 'date', width: 'third' },
        { id: 'cycle_days', label: '주기', kind: 'number', unit: '일', width: 'third' },
        { id: 'menses_days', label: '월경기간', kind: 'number', unit: '일', width: 'third' },
        { id: 'clots', label: '혈괴(血塊)', kind: 'radio', options: ['없음', '소량', '과다'], width: 'half' },
        { id: 'flow_pads', label: '월경량(패드 총 사용량)', kind: 'number', unit: '개', width: 'half' },
        {
          id: 'flow_pad_type',
          label: '패드 종류',
          kind: 'checks',
          options: ['오버나이트', '대형', '중형'],
          width: 'full',
        },
        { id: 'pain_duration', label: '통증기간', kind: 'number', unit: '시간', width: 'third' },
        { id: 'pain_intensity', label: '통증강도', kind: 'number', unit: '/10', width: 'third' },
        { id: 'painkiller', label: '진통제 복용', kind: 'number', unit: '정', width: 'third' },
        {
          id: 'menses_symptoms',
          label: '수반증상',
          kind: 'checks',
          options: ['오심', '구토', '설사', '방산통', '두통', '부종'],
          allowOther: true,
          width: 'full',
        },
      ],
    },
    {
      id: 'ovulation_change',
      title: '배란 후 변화',
      fields: [
        { id: 'cervical_mucus', label: '경관점액 변화', kind: 'radio', options: YESNO, width: 'third' },
        { id: 'discharge_amount', label: '대하량', kind: 'radio', options: ['적다', '보통', '많다'], width: 'third' },
        { id: 'breast_change', label: '유방변화', kind: 'radio', options: YESNO, width: 'third' },
        { id: 'odor', label: '취기', kind: 'radio', options: YESNO, width: 'third' },
        { id: 'abdominal_bloating', label: '복부팽만감', kind: 'radio', options: YESNO, width: 'third' },
        { id: 'mucus_consistency', label: '점조상태', kind: 'radio', options: ['묽다', '끈끈하다'], width: 'third' },
      ],
    },
    {
      id: 'systemic',
      title: '전신기능 문진',
      fields: [
        { id: 'sx_headache', label: '두통', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_dizziness', label: '현훈', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_stress', label: '스트레스', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_fatigue', label: '피로', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_insomnia', label: '불면', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_pain', label: '통증', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_digestion', label: '소화', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_heat', label: '열감', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_cold', label: '냉감', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        {
          id: 'psych',
          label: '정신과적 증상',
          kind: 'checks',
          options: ['정상', '불안', '우울', '긴장', '분노'],
          allowOther: true,
          width: 'full',
        },
        { id: 'stool', label: '대변', kind: 'text', width: 'third' },
        { id: 'urine', label: '소변', kind: 'text', width: 'third' },
        { id: 'body_temp', label: '체온', kind: 'number', unit: '℃', width: 'third' },
      ],
    },
    {
      id: 'physical_exam',
      title: '신체검진 (망문문절)',
      fields: [
        { id: 'exam_complexion', label: '면색', kind: 'text', width: 'half' },
        { id: 'exam_pulse', label: '맥진', kind: 'text', width: 'half' },
        { id: 'exam_tongue', label: '설진', kind: 'text', width: 'half' },
        { id: 'exam_abdomen', label: '복진', kind: 'text', width: 'half' },
      ],
    },
    {
      id: 'diagnosis',
      title: '진단 및 변증',
      fields: [
        {
          id: 'dx_cause',
          label: '난임 변병',
          kind: 'checks',
          options: INFERTILITY_CAUSE,
          allowOther: true,
          required: true,
          width: 'full',
        },
        {
          id: 'pattern',
          label: '변증(여성)',
          kind: 'checks',
          options: PATTERN_FEMALE,
          allowOther: true,
          required: true,
          width: 'full',
        },
      ],
    },
    treatmentSection('init'),
  ],
}
