// 한의 난임 진료부(남성용) 초진 챠트 — ver4.0 PDF 1~6p 디지털화
import {
  GOOD_LOW_NONE,
  INFERTILITY_CAUSE,
  PATTERN_MALE,
  SCALE_OPTIONS,
  treatmentSection,
  type FormSchema,
} from './schema'

export const maleInitial: FormSchema = {
  type: 'initial_male',
  title: '한의 난임 진료부(남성용) · 초진',
  sections: [
    {
      id: 'general',
      title: '일반정보 · 신체정보 · 기호품',
      fields: [
        { id: 'visit_date', label: '초진일자', kind: 'date', width: 'third', required: true },
        { id: 'height', label: '키', kind: 'number', unit: 'cm', width: 'third' },
        { id: 'weight', label: '몸무게', kind: 'number', unit: 'kg', width: 'third' },
        { id: 'caffeine', label: '커피 등 카페인음료', kind: 'text', unit: '잔/일', width: 'half' },
        { id: 'meds', label: '복용 중 약물', kind: 'text', width: 'half' },
        { id: 'alcohol', label: '음주', kind: 'text', placeholder: '술 ○병/회, 월 ○회', width: 'half' },
        {
          id: 'smoking',
          label: '흡연',
          kind: 'radio',
          options: ['비흡연', '금연', '흡연'],
          width: 'half',
        },
        { id: 'smoking_amount', label: '흡연량(흡연 시)', kind: 'text', unit: '개피/일', width: 'half' },
        { id: 'comorbidity', label: '동반질환', kind: 'textarea', width: 'full' },
        { id: 'surgery_history', label: '수술력', kind: 'textarea', width: 'full' },
      ],
    },
    {
      id: 'marriage_birth',
      title: '결혼 및 출산력',
      fields: [
        { id: 'marriage_period', label: '결혼기간', kind: 'number', unit: '개월', width: 'third' },
        { id: 'ttc_start', label: '임신시도 시작', kind: 'number', unit: '개월 전', width: 'third' },
        { id: 'contraception_period', label: '피임기간', kind: 'number', unit: '개월', width: 'third' },
        {
          id: 'intercourse_freq',
          label: '성생활 빈도',
          kind: 'text',
          placeholder: '평균 ○회/월 (배란 전/당일/후)',
          width: 'full',
        },
        {
          id: 'contraception_method',
          label: '피임방법',
          kind: 'checks',
          options: [
            '경구 피임제',
            '주사용 피임제',
            '피하 이식 피임제',
            '자궁 내 피임장치',
            '콘돔',
            '질외사정',
            '날짜 피임법',
          ],
          allowOther: true,
          width: 'full',
        },
        {
          id: 'obstetric_history',
          label: '산과력 (만삭-조산-유산-생존자녀)',
          kind: 'text',
          placeholder: '( ) - ( ) - ( ) - ( )',
          width: 'full',
        },
        {
          id: 'birth_history',
          label: '출산력 (출산시기 / 임신방법 / 출산방법)',
          kind: 'textarea',
          width: 'full',
        },
      ],
    },
    {
      id: 'semen_sexual',
      title: '남성 정액검사 및 성기능 평가',
      fields: [
        { id: 'dx_first_org', label: '난임 최초 진단기관명', kind: 'text', width: 'half' },
        { id: 'dx_time', label: '진단시기', kind: 'text', placeholder: 'YYYY-MM', width: 'half' },
        { id: 'h_semen', label: '— 정액검사 (최근검사일 포함) —', kind: 'heading' },
        { id: 'semen_volume', label: '정액량', kind: 'number', unit: 'mL', width: 'half', note: '참고치 하한 1.5mL' },
        { id: 'semen_count', label: '정자수(사정당)', kind: 'text', width: 'half', note: '참고치 하한 39×10⁶' },
        { id: 'semen_motility', label: '정자운동성', kind: 'number', unit: '%', width: 'half', note: '참고치 하한 >40%' },
        { id: 'semen_morphology', label: '정상정자 형태', kind: 'number', unit: '% (NF)', width: 'half', note: '참고치 하한 4' },
        { id: 'h_sexual', label: '— 성기능 평가 —', kind: 'heading' },
        { id: 'libido', label: '성욕', kind: 'radio', options: GOOD_LOW_NONE, width: 'third' },
        { id: 'erection', label: '발기력', kind: 'radio', options: GOOD_LOW_NONE, width: 'third' },
        {
          id: 'ejaculation',
          label: '사정',
          kind: 'radio',
          options: ['양호', '지연', '조루', '통증'],
          allowOther: true,
          width: 'third',
        },
      ],
    },
    {
      id: 'systemic',
      title: '전신기능 문진',
      fields: [
        { id: 'sx_headache', label: '두통', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_dizziness', label: '현훈', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_stress', label: '스트레스', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_fatigue', label: '피로', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_sleep', label: '수면', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_pain', label: '통증', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_digestion', label: '소화', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_heat', label: '열감', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        { id: 'sx_cold', label: '냉감', kind: 'scale', options: SCALE_OPTIONS, width: 'half' },
        {
          id: 'psych',
          label: '정신과적 증상',
          kind: 'checks',
          options: ['정상', '불안', '우울', '긴장', '분노'],
          allowOther: true,
          width: 'full',
        },
        { id: 'stool', label: '대변', kind: 'text', width: 'third' },
        { id: 'urine', label: '소변', kind: 'text', width: 'third' },
        { id: 'body_temp', label: '체온', kind: 'number', unit: '℃', width: 'third' },
      ],
    },
    {
      id: 'physical_exam',
      title: '신체검진 (망문문절)',
      fields: [
        { id: 'exam_complexion', label: '면색', kind: 'text', width: 'half' },
        { id: 'exam_pulse', label: '맥진', kind: 'text', width: 'half' },
        { id: 'exam_tongue', label: '설진', kind: 'text', width: 'half' },
        { id: 'exam_abdomen', label: '복진', kind: 'text', width: 'half' },
      ],
    },
    {
      id: 'diagnosis',
      title: '진단 및 변증',
      fields: [
        {
          id: 'dx_cause',
          label: '난임 변병',
          kind: 'checks',
          options: INFERTILITY_CAUSE,
          allowOther: true,
          required: true,
          width: 'full',
        },
        {
          id: 'pattern',
          label: '변증(남성)',
          kind: 'checks',
          options: PATTERN_MALE,
          allowOther: true,
          required: true,
          width: 'full',
        },
      ],
    },
    treatmentSection('init'),
  ],
}
